default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: '^example/.*$'
      - id: terraform_tflint
        exclude: '^example/.*$'
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml terraform
      - id: terraform_tfsec
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.*/README.md' # terraform-docs requires a trailing comment with a newline
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
